"""empty message

Revision ID: 01818444d929
Revises: ae07eef38e43
Create Date: 2026-04-11 00:35:35.229496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01818444d929'
down_revision = 'ae07eef38e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###