"""change profile_picture_url to Text

Revision ID: 608321ef9136
Revises: 01818444d929
Create Date: 2026-04-13 22:44:44.440379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608321ef9136'
down_revision = '01818444d929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
