"""Add bio, genre, favorite_game, and playstyle to User

Revision ID: 75720ba1ca47
Revises: 01818444d929
Create Date: 2026-04-13 15:24:27.868453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75720ba1ca47'
down_revision = '01818444d929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_genre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('playstyle', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('favorite_game', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_game')
        batch_op.drop_column('playstyle')
        batch_op.drop_column('preferred_genre')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
